/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisbursementsRouteImport } from './routes/disbursements'
import { Route as BeneficiariesBeneficiaryIdRouteImport } from './routes/beneficiaries/$beneficiaryId'
import { Route as BeneficiariesNewRouteImport } from './routes/beneficiaries/new'
import { Route as ProgramsProgramIdBeneficiariesRouteImport } from './routes/programs/$programId/beneficiaries'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisbursementsRoute = DisbursementsRouteImport.update({
  id: '/disbursements',
  path: '/disbursements',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiariesBeneficiaryIdRoute =
  BeneficiariesBeneficiaryIdRouteImport.update({
    id: '/beneficiaries/$beneficiaryId',
    path: '/beneficiaries/$beneficiaryId',
    getParentRoute: () => rootRouteImport,
  } as any)
const BeneficiariesNewRoute = BeneficiariesNewRouteImport.update({
  id: '/beneficiaries/new',
  path: '/beneficiaries/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsProgramIdBeneficiariesRoute =
  ProgramsProgramIdBeneficiariesRouteImport.update({
    id: '/programs/$programId/beneficiaries',
    path: '/programs/$programId/beneficiaries',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disbursements': typeof DisbursementsRoute
  '/beneficiaries/$beneficiaryId': typeof BeneficiariesBeneficiaryIdRoute
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/programs/$programId/beneficiaries': typeof ProgramsProgramIdBeneficiariesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disbursements': typeof DisbursementsRoute
  '/beneficiaries/$beneficiaryId': typeof BeneficiariesBeneficiaryIdRoute
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/programs/$programId/beneficiaries': typeof ProgramsProgramIdBeneficiariesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disbursements': typeof DisbursementsRoute
  '/beneficiaries/$beneficiaryId': typeof BeneficiariesBeneficiaryIdRoute
  '/beneficiaries/new': typeof BeneficiariesNewRoute
  '/programs/$programId/beneficiaries': typeof ProgramsProgramIdBeneficiariesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/disbursements'
    | '/beneficiaries/$beneficiaryId'
    | '/beneficiaries/new'
    | '/programs/$programId/beneficiaries'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/disbursements'
    | '/beneficiaries/$beneficiaryId'
    | '/beneficiaries/new'
    | '/programs/$programId/beneficiaries'
  id:
    | '__root__'
    | '/'
    | '/disbursements'
    | '/beneficiaries/$beneficiaryId'
    | '/beneficiaries/new'
    | '/programs/$programId/beneficiaries'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisbursementsRoute: typeof DisbursementsRoute
  BeneficiariesBeneficiaryIdRoute: typeof BeneficiariesBeneficiaryIdRoute
  BeneficiariesNewRoute: typeof BeneficiariesNewRoute
  ProgramsProgramIdBeneficiariesRoute: typeof ProgramsProgramIdBeneficiariesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disbursements': {
      id: '/disbursements'
      path: '/disbursements'
      fullPath: '/disbursements'
      preLoaderRoute: typeof DisbursementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries/$beneficiaryId': {
      id: '/beneficiaries/$beneficiaryId'
      path: '/beneficiaries/$beneficiaryId'
      fullPath: '/beneficiaries/$beneficiaryId'
      preLoaderRoute: typeof BeneficiariesBeneficiaryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficiaries/new': {
      id: '/beneficiaries/new'
      path: '/beneficiaries/new'
      fullPath: '/beneficiaries/new'
      preLoaderRoute: typeof BeneficiariesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$programId/beneficiaries': {
      id: '/programs/$programId/beneficiaries'
      path: '/programs/$programId/beneficiaries'
      fullPath: '/programs/$programId/beneficiaries'
      preLoaderRoute: typeof ProgramsProgramIdBeneficiariesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisbursementsRoute: DisbursementsRoute,
  BeneficiariesBeneficiaryIdRoute: BeneficiariesBeneficiaryIdRoute,
  BeneficiariesNewRoute: BeneficiariesNewRoute,
  ProgramsProgramIdBeneficiariesRoute: ProgramsProgramIdBeneficiariesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
